# Generated by Django 2.2.3 on 2019-09-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('deliveries_made', models.IntegerField()),
                ('money_earned', models.DecimalField(decimal_places=2, max_digits=9)),
                ('license_plate_number', models.CharField(max_length=10)),
                ('car_make', models.CharField(max_length=16)),
                ('car_model', models.CharField(max_length=16)),
                ('license_identifier_number', models.CharField(max_length=12)),
                ('state_of_drivers_license_issuance', models.CharField(max_length=25)),
                ('credit_card_number', models.IntegerField()),
                ('security_number', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('order_start_time', models.TimeField()),
                ('order_deliver_time', models.TimeField()),
                ('current_store_to_go_to', models.CharField(max_length=20)),
                ('current_order_list', models.CharField(max_length=255)),
                ('current_order_size', models.CharField(max_length=15)),
                ('special_requests', models.CharField(max_length=150)),
                ('is_on_the_way_to_the_store', models.BooleanField(default=True)),
                ('is_at_the_store', models.BooleanField(default=False)),
                ('is_on_the_way_from_the_store', models.BooleanField(default=False)),
                ('current_address_dropoff_street_and_street_number', models.CharField(max_length=35)),
                ('customer_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('delivery_address', models.CharField(max_length=50)),
                ('delivery_apt_suite', models.CharField(max_length=20)),
                ('delivery_instructions', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('activate_favorite_store', models.BooleanField(default=False)),
                ('favorite_store', models.CharField(choices=[('KRO', 'Kroger'), ('Wal', 'Wal-Mart')], default=None, max_length=15)),
                ('credit_card_number', models.IntegerField()),
                ('security_number', models.IntegerField()),
                ('store_selection', models.CharField(choices=[('KRO', 'Kroger'), ('Wal', 'Wal-Mart')], default=None, max_length=15)),
                ('order_size', models.CharField(max_length=15)),
                ('order_list', models.CharField(max_length=255)),
                ('desired_delivery_time_range_lower_bound', models.TimeField()),
                ('desired_delivery_time_range_upper_bound', models.TimeField()),
                ('is_delivery_asap', models.BooleanField(default=False)),
            ],
        ),
    ]
