# Generated by Django 2.2.4 on 2019-10-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=50)),
                ('delivery_apt_suite', models.CharField(max_length=20)),
                ('delivery_instructions', models.CharField(max_length=120)),
                ('dropoff_latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('dropoff_longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('driver_latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('driver_longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('store_selection', models.CharField(choices=[('KRO', 'Kroger'), ('WAL', 'Wal-Mart')], default=None, max_length=15)),
                ('order_size', models.CharField(max_length=15)),
                ('order_list', models.CharField(max_length=255)),
                ('desired_delivery_time_range_lower_bound', models.TimeField()),
                ('desired_delivery_time_range_upper_bound', models.TimeField()),
                ('is_delivery_asap', models.BooleanField(default=False)),
                ('order_start_time', models.TimeField()),
                ('order_deliver_time', models.TimeField()),
                ('current_store_to_go_to', models.CharField(max_length=20)),
                ('special_requests', models.CharField(max_length=150)),
                ('is_on_the_way_to_the_store', models.BooleanField(default=True)),
                ('is_at_the_store', models.BooleanField(default=False)),
                ('is_on_the_way_from_the_store', models.BooleanField(default=False)),
                ('current_address_dropoff_street_and_street_number', models.CharField(max_length=35)),
                ('customer_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='current_address_dropoff_street_and_street_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='current_order_list',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='current_order_size',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='current_store_to_go_to',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_at_the_store',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_on_the_way_from_the_store',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_on_the_way_to_the_store',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='order_deliver_time',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='order_start_time',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='security_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activate_favorite_store',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delivery_apt_suite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delivery_instructions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='desired_delivery_time_range_lower_bound',
        ),
        migrations.RemoveField(
            model_name='user',
            name='desired_delivery_time_range_upper_bound',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_store',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_delivery_asap',
        ),
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='order_list',
        ),
        migrations.RemoveField(
            model_name='user',
            name='order_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='security_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='store_selection',
        ),
    ]
