# Generated by Django 2.2.5 on 2019-10-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191021_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
