# Generated by Django 2.2.5 on 2019-10-21 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField()),
                ('deliveries_made', models.IntegerField()),
                ('money_earned', models.DecimalField(decimal_places=2, max_digits=9)),
                ('license_plate_number', models.CharField(max_length=10)),
                ('car_make', models.CharField(max_length=16)),
                ('car_model', models.CharField(max_length=16)),
                ('license_identifier_number', models.CharField(max_length=12)),
                ('state_of_drivers_license_issuance', models.CharField(max_length=25)),
                ('is_matching', models.BooleanField()),
                ('driver_filled', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
