# Generated by Django 2.2.5 on 2019-10-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191023_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deliveries_made',
            field=models.IntegerField(default=0),
        ),
    ]
