# Generated by Django 2.2.5 on 2019-10-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191023_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='car_make',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='car_model',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='driver_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_matching',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='license_identifier_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='license_plate_number',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='money_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state_of_drivers_license_issuance',
            field=models.CharField(default='', max_length=25),
        ),
    ]
