# Generated by Django 2.2.5 on 2019-10-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_has_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.CharField(default='', max_length=20),
        ),
    ]
