# Generated by Django 2.2.5 on 2019-10-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191026_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_order',
            field=models.CharField(default='', max_length=50),
        ),
    ]
