# Generated by Django 2.2.5 on 2019-10-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191027_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_address_dropoff_street_and_street_number',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_store_to_go_to',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='desired_delivery_time_range_lower_bound',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='desired_delivery_time_range_upper_bound',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_latitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_longitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='dropoff_latitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='dropoff_longitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_deliver_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_list',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_size',
            field=models.CharField(default='small', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_start_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_requests',
            field=models.CharField(default='', max_length=150),
        ),
    ]
