# Generated by Django 2.2.5 on 2019-10-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191027_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_list',
        ),
    ]
