# Generated by Django 2.2.5 on 2019-10-27 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_order_order_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_deliver_time',
            field=models.TimeField(default=datetime.datetime(2019, 10, 27, 21, 41, 38, 995377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_start_time',
            field=models.TimeField(default=datetime.datetime(2019, 10, 27, 21, 41, 38, 995377, tzinfo=utc)),
        ),
    ]
