# Generated by Django 2.2.5 on 2019-10-27 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191027_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='desired_delivery_time_range_lower_bound',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='desired_delivery_time_range_upper_bound',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_deliver_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
