# Generated by Django 2.2.5 on 2019-10-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20191027_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
