# Generated by Django 2.2.5 on 2019-10-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_order_order_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_order',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_shopping',
            field=models.BooleanField(default=False),
        ),
    ]
