# Generated by Django 2.2.5 on 2019-10-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20191027_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_list',
            field=models.CharField(default='cheese', max_length=1000),
        ),
    ]
