# Generated by Django 2.2.5 on 2019-11-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20191109_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_cost',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
    ]
