# Generated by Django 2.2.7 on 2019-11-10 18:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20191109_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
