# Generated by Django 2.2.7 on 2019-11-10 19:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20191110_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'items': {}}, null=True),
        ),
    ]
