# Generated by Django 2.2.7 on 2019-11-10 20:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20191110_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'items': []}),
        ),
    ]
