# Generated by Django 2.2.5 on 2019-11-11 14:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_order_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=users.models.get_default_cart),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=users.models.get_default_cart),
        ),
    ]
