# Generated by Django 2.2.5 on 2019-11-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_order_has_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='has_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
